select * from customer limit 1
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM (purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, "purchase_amount_(usd)"
FROM customer
WHERE discount_applied = 'Yes'
AND "purchase_amount_(usd)" > (
    SELECT AVG("purchase_amount_(usd)") FROM customer
);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_purchase
FROM customer
GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_spend,
    ROUND(SUM("purchase_amount_(usd)"), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*), 2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT customer_segment, COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers DESC;
-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
),

ranked_items AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)

SELECT category, item_purchased, total_orders
FROM ranked_items
WHERE item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(*) AS total_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
       SUM("purchase_amount_(usd)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
